### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by koalalorenzo** [cryptohagen/cryptohagen.github.io#2]
Are you thinking to write this website only in danish? 
What about english too?

**Comment by benjaoming** [comment]
great idea!

right now it's pretty stack-free, what's a good approach of making a multi-lingual stack-free website? Just clone `index.html` to `index-en.html`?

Does it scale? Do we care?

**Comment by koalalorenzo** [comment]
It depends if you want to attract more developers or not. I do care because I wish I could help in danish :( but I can't 

"_scale_" LoL

**Comment by benjaoming** [comment]
that WAS a joke :D

I don't know about the relevance of English, but I guess if there's a page in English, then non-Danes might come, and then it would be like a self-fulfilling prophecy.. let's at least give it a try if someone wants to make the effort to make it work.

**Comment by ghost** [comment]
I agree that we should probably provide at least some basic info in English.

**Comment by vanjacosic** [comment]
I made a PR during yesterday's meetup which added the necessary templating and translation changes. (There's now an English option in the menu)
More work could be done, but it's a good start. It was merged and is live :) 
So I guess this can be closed.
